import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers  from '../providers';
import { AuthProvider } from "@/features/auth";
import "./globals.css";
import { cookies } from "next/headers";
import { UserType } from "@/features/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getMe(): Promise<UserType | null>{
  const cookiesStore = await cookies();

  const token = cookiesStore.get("token")?.value;

  if(!token) return null;

  try {
    const response = await fetch(`${process.env.BASE_URL}/auth/me`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
      method: 'GET',
    });
    return await response.json();
  } catch {
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getMe();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} font-sans h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <Providers>
            <AuthProvider initialUser={user}>
                {children}
            </AuthProvider>
          </Providers>
        </body>
    </html>
  );
}
