

export enum Cargo {
  ADMIN = 'ADMIN',
  COORDENADOR_GERAL = 'COORDENADOR_GERAL',
  FORMADOR = 'FORMADOR',
  COORDENADOR_FREQUENCIA = 'COORDENADOR_FREQUENCIA',
  COORDENADOR_CAIXINHA = 'COORDENADOR_CAIXINHA',
  COORDENADOR_COMUNICACAO = 'COORDENADOR_COMUNICACAO',
  COORDENADOR_MUSICA = 'COORDENADOR_MUSICA',
  COORDENADOR_PESCARIA = 'COORDENADOR_PESCARIA',
  COORDENADOR_LEMBRANCINHA = 'COORDENADOR_LEMBRANCINHA',
  COORDENADOR_INTERCESSAO = 'COORDENADOR_INTERCESSAO',
  ANIMADOR_FREQUENCIA = 'ANIMADOR_FREQUENCIA',
  ANIMADOR_CAIXINHA = 'ANIMADOR_CAIXINHA',
  ANIMADOR_PESCARIA = 'ANIMADOR_PESCARIA',
  ANIMADOR_COMUNICACAO = 'ANIMADOR_COMUNICACAO',
  ANIMADOR_MUSICA = 'ANIMADOR_MUSICA',
  ANIMADOR_LEMBRANCINHA = 'ANIMADOR_LEMBRANCINHA',
  ANIMADOR_INTERCESSAO = 'ANIMADOR_INTERCESSAO',
  ANIMADOR = 'ANIMADOR',
}

export type CargosLista = keyof typeof Cargo;