

export enum Cargo {
  COORDENADOR_GERAL= "COORDENADOR_GERAL",
  FORMADOR = 'FORMADOR',
  COORDENADOR_FREQUENCIA = 'COORDENADOR_FREQUENCIA',
  COORDENADOR_CAIXINHA = 'COORDENADOR_CAIXINHA',
  ANIMADOR_FREQUENCIA = 'ANIMADOR_FREQUENCIA',
  ANIMADOR_CAIXINHA = 'ANIMADOR_CAIXINHA',
  ANIMADOR = 'ANIMADOR'
}